---
parent: Api_v1_bank-account_withdraw-amount
name: ApiV1BankAccountWithdrawAmountPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/bank-account/withdraw-amount
endpoint: /api/v1/bank-account/withdraw-amount
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "accountBalance" : "{{@RandomInteger}}",
      "accountNumber" : "{{@RandomInteger}}",
      "createdBy" : "",
      "createdDate" : "",
      "id" : "",
      "inactive" : false,
      "modifiedBy" : "",
      "modifiedDate" : "",
      "user" : {
        "createdBy" : "",
        "createdDate" : "",
        "id" : "",
        "inactive" : false,
        "modifiedBy" : "",
        "modifiedDate" : "",
        "name" : "{{@Random}}",
        "version" : ""
      },
      "version" : ""
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- OWASP-OriginHeaderScrutiny
- OWASP-API7
- Misconfiguration
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
